// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw9UriKxkurIsD0APA7EDhwvXCpnBAR54',
    appId: '1:809038640860:web:272a4fedbb348a292de619',
    messagingSenderId: '809038640860',
    projectId: 'easy-browse-5ffbe',
    authDomain: 'easy-browse-5ffbe.firebaseapp.com',
    storageBucket: 'easy-browse-5ffbe.firebasestorage.app',
    measurementId: 'G-STJD5MQTZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Bm7Yqt6iCx5VZQ9gE89ES1pQP8QXv6M',
    appId: '1:809038640860:android:ee57664521fbda282de619',
    messagingSenderId: '809038640860',
    projectId: 'easy-browse-5ffbe',
    storageBucket: 'easy-browse-5ffbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUO5pLBVGjwTzKaZOZ12amRBqWRNH31rY',
    appId: '1:809038640860:ios:b9e8bae0d4d2078f2de619',
    messagingSenderId: '809038640860',
    projectId: 'easy-browse-5ffbe',
    storageBucket: 'easy-browse-5ffbe.firebasestorage.app',
    iosBundleId: 'com.example.easyBrowse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUO5pLBVGjwTzKaZOZ12amRBqWRNH31rY',
    appId: '1:809038640860:ios:b9e8bae0d4d2078f2de619',
    messagingSenderId: '809038640860',
    projectId: 'easy-browse-5ffbe',
    storageBucket: 'easy-browse-5ffbe.firebasestorage.app',
    iosBundleId: 'com.example.easyBrowse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw9UriKxkurIsD0APA7EDhwvXCpnBAR54',
    appId: '1:809038640860:web:c6338af2e31c92652de619',
    messagingSenderId: '809038640860',
    projectId: 'easy-browse-5ffbe',
    authDomain: 'easy-browse-5ffbe.firebaseapp.com',
    storageBucket: 'easy-browse-5ffbe.firebasestorage.app',
    measurementId: 'G-QCL2K65LJR',
  );
}
